exclude: ^(?:\.cache/|runs/|outputs/|\.venv/|tmp_.*|.*\.egg-info/)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        # Run mypy in strict mode against the package directory
        # rather than per-file to avoid partial checks.
        pass_filenames: false
        args: ["--config-file", "mypy.ini", "--strict", "src/constelx"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
