{
  "run": {
    "nfp": 3,
    "seed": 0,
    "out_dir": "runs/p1_micro",
    "algo": "random",
    "budget": 3,
    "resume": null,
    "max_workers": 1,
    "cache_dir": null,
    "correction": null,
    "constraints": null,
    "use_physics": true,
    "pcfm_gn_iters": null,
    "pcfm_damping": null,
    "pcfm_tol": null,
    "problem": "p1",
    "init_seeds": "data/seeds.jsonl"
  },
  "env": {
    "python": "3.12.3",
    "platform": "darwin",
    "cwd": "/Users/suhjungdae/code/software/proxima_fusion/constelx_starter"
  },
  "git": {
    "sha": "a0765c113f30c7482ff022f8949f23dbec982195"
  },
  "versions": {
    "constelx": "0.0.1",
    "numpy": "2.1.3",
    "pandas": "2.2.3",
    "constellaration": "0.2.3"
  }
}