name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  core:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Ruff format (check)
        run: ruff format --check .
      - name: Ruff lint
        run: ruff check .
      - name: Mypy type check
        run: mypy src/constelx
      - name: Pytest
        run: pytest -q
  physics:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install system deps (NetCDF, cmake, ninja)
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev libnetcdf-c++4-dev cmake ninja-build
      - name: Install dependencies (physics extra)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,physics]"
      - name: Pytest
        run: pytest -q
