name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: System deps for constellaration forward model
        run: sudo apt-get update && sudo apt-get install -y libnetcdf-dev
      - name: Install
        run: pip install -e ".[dev]"
      - name: Lint
        run: ruff check .
      - name: Type check
        run: |
          pip install mypy
          mypy
      - name: Tests
        run: pytest -q
