name: real-smoke

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/constelx/eval/**'
      - 'src/constelx/physics/**'

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev netcdf-bin
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,physics]'
      - name: Verify real evaluator available
        run: |
          python - <<'PY'
          from importlib import import_module

          for mod in [
              "constellaration",
              "constelx.physics.constel_api",
          ]:
              import_module(mod)
          PY
      - name: Cache evaluator results
        uses: actions/cache@v4
        with:
          path: .cache/eval
          key: ${{ runner.os }}-eval-cache
          restore-keys: |
            ${{ runner.os }}-eval-
      - name: Real smoke run
        env:
          CONSTELX_USE_REAL_EVAL: "1"
          CONSTELX_ENFORCE_REAL: "1"
        run: |
          constelx agent run --nfp 3 --budget 3 --use-physics --problem p1 --seed 0 --limit 8 --runs-dir runs/smoke
      - name: Check provenance
        run: |
          python - <<'PY'
          from pathlib import Path

          from constelx.metrics import ensure_real_metrics_csv

          run_root = next(Path('runs/smoke').glob('*'))
          ensure_real_metrics_csv(run_root / 'metrics.csv')
          PY
